GET http://localhost:5000/Users


###
PATCH http://localhost:5000/Users/47
Content-Type: application/json

{
    "nama": "wdwdwdw",
    "username": "wdwdwdw",
    "password": "wdwdwdw",
    "role": "Karyawan",
    "email": "wdwdwdw@gmail.com",
    "no_telepon": 89519113444
}

###
POST http://localhost:5000/Users
Content-Type: application/json

{
    "nama": "wokwok",
    "username": "wokwok",
    "password": "wokwok",
    "role": "wokwok",
    "email": "wokwok@gmail.com",
    "no_telepon": 89519113444
}

###
POST http://localhost:5000/Login
Content-Type: application/json

{
    "username": "SuperAdmin",
    "password": "SuperAdmin"
}

###
GET http://localhost:5000/getMe

###
GET   http://localhost:5000/Logout

###
POST    http://localhost:5000/blockUser/43

###
PATCH http://localhost:5000/deletedUser/47