GET http://localhost:5000/Users

###


POST http://localhost:5000/Users
Content-Type: application/json

{
    "nama": "tes",
    "username": "tes",
    "password": "tes",
    "confPassword": "tes",
    "role": "tes",
    "email": "tes@gmail.com",
    "no_telepon": 89519113444
}

###
POST http://localhost:5000/Login
Content-Type: application/json

{
    "username": "tes",
    "password": "tes"
}

###
GET http://localhost:5000/getMe

###
GET   http://localhost:5000/Logout